// frontend/src/components/browse/sections/index.js
export { default as AppDownloadSection }    from "./AppDownloadSection";
export { default as CalendarSection }       from "./CalendarSection";
export { default as CategoryNavSection }    from "./CategoryNavSection";
export { default as EditorsPicksSection }   from "./EditorsPicksSection";
export { default as EventGridSection }      from "./EventGridSection";
export { default as FeaturedSection }       from "./FeaturedSection";
export { default as FiltersSection }        from "./FiltersSection";
export { default as BrowsePageLayout }      from "./BrowsePageLayout";
export { default as HeroSection }           from "./HeroSection";
export { default as MapSection }            from "./MapSection";
export { default as NearbySection }         from "./NearbySection";
export { default as NewArrivalsSection }    from "./NewArrivalsSection";
export { default as NewsletterSection }     from "./NewsletterSection";
export { default as RecommendedSection }    from "./RecommendedSection";
export { default as ReviewsSection }        from "./ReviewsSection";
export { default as SearchBar }             from "./SearchBar";
export { default as StatsSection }          from "./StatsSection";
export { default as TopRatedSection }       from "./TopRatedSection";
export { default as TrendingSection }       from "./TrendingSection";
export { default as UpcomingSection }       from "./UpcomingSection";
export { default as SectionShell }          from "./SectionShell";
// Stub sections (kept for compatibility)
export { default as BreadcrumbSection }     from "./BreadcrumbSection";
export { default as EventDetailsSection }   from "./EventDetailsSection";
export { default as EventScheduleSection }  from "./EventScheduleSection";
export { default as FAQSection }            from "./FAQSection";
export { default as GuideSection }          from "./GuideSection";
export { default as PriceRangeSection }     from "./PriceRangeSection";
export { default as RecentlyViewedSection } from "./RecentlyViewedSection";
export { default as RelatedEventsSection }  from "./RelatedEventsSection";
export { default as SubcategoryNavSection } from "./SubcategoryNavSection";
export { default as TicketSection }         from "./TicketSection";
export { default as VenueHighlightsSection }from "./VenueHighlightsSection";
export { default as VenueSection }          from "./VenueSection";
export { default as CategoryGridSection }   from "./CategoryGridSection";
