import authConfig from "./auth.config";

export const API_BASE_URL = authConfig.apiBaseUrl;

export const ENDPOINTS = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    LOGOUT: "/auth/logout",
    LOGOUT_ALL: "/auth/logout-all",
    REFRESH_TOKEN: "/auth/refresh-token",
    ME: "/auth/me",
    VERIFY_EMAIL: "/auth/verify-email",
    RESEND_VERIFICATION: "/auth/resend-verification",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    CHANGE_PASSWORD: "/auth/change-password",
    SESSIONS: "/auth/sessions",
    SESSION: (id) => `/auth/sessions/${id}`,
    TWO_FACTOR: {
      SETUP: "/auth/2fa/setup",
      ENABLE: "/auth/2fa/enable",
      DISABLE: "/auth/2fa/disable",
      VERIFY: "/auth/2fa/verify",
    },
    OAUTH: {
      GOOGLE: "/auth/oauth/google",
      FACEBOOK: "/auth/oauth/facebook",
    },
  },

  USERS: {
    ME: "/users/me",
    AVATAR: "/users/me/avatar",
    SESSIONS: "/users/me/sessions",
    SESSION: (id) => `/users/me/sessions/${id}`,
    LIST: "/users",
    STATS: "/users/stats",
    DETAIL: (id) => `/users/${id}`,
    ACTIVATE: (id) => `/users/${id}/activate`,
    DEACTIVATE: (id) => `/users/${id}/deactivate`,
    ROLE: (id) => `/users/${id}/role`,
  },

  EVENTS: {
    LIST: "/events",
    FEATURED: "/events/featured",
    TRENDING: "/events/trending",
    OFFERS: "/events/offers",
    UPCOMING: "/events/upcoming",
    ADMIN_LIST: "/events/admin/all",
    DETAIL: (slug) => `/events/${slug}`,
    DETAILS: (slug) => `/events/${slug}/details`,
    TICKETS: (slug) => `/events/${slug}/tickets`,
    REVIEWS: (slug) => `/events/${slug}/reviews`,
    TICKET_TYPES: (slug) => `/events/${slug}/ticket-types`,
    TICKET_TYPE: (slug, id) => `/events/${slug}/ticket-types/${id}`,
    RELATED: (slug) => `/events/${slug}/related`,
    SEAT_SECTIONS: (slug) => `/events/${slug}/seat-sections`,
    SEAT_SECTION: (slug, id) => `/events/${slug}/seat-sections/${id}`,
    SEAT_MAP: (slug) => `/events/${slug}/seat-map`,
    FACETS: "/events/facets",
    NEARBY: "/events/near",
    CREATE: "/events",
    UPDATE: (slug) => `/events/${slug}`,
    DELETE: (slug) => `/events/${slug}`,
    PUBLISH: (slug) => `/events/${slug}/publish`,
    CANCEL: (slug) => `/events/${slug}/cancel`,
    APPROVE: (slug) => `/events/${slug}/approve`,
    REJECT: (slug) => `/events/${slug}/reject`,
    LIKE: (slug) => `/events/${slug}/like`,
    BOOKMARK: (slug) => `/events/${slug}/bookmark`,
    SHARE: (slug) => `/events/${slug}/share`,
    VIEW: (slug) => `/events/${slug}/view`,
    // Image upload (Cloudinary)
    COVER_IMAGE: (slug) => `/events/${slug}/images/cover`,
    GALLERY_IMAGES: (slug) => `/events/${slug}/images/gallery`,
    GALLERY_IMAGE_BATCH: (slug) => `/events/${slug}/images/gallery/batch`,
    GALLERY_IMAGE_ORDER: (slug) => `/events/${slug}/images/gallery`,
  },

  BOOKINGS: {
    LIST: "/bookings",
    CREATE: "/bookings",
    DETAIL: (ref) => `/bookings/${ref}`,
    CANCEL: (ref) => `/bookings/${ref}/cancel`,
    REFUND: (ref) => `/bookings/${ref}/refund`,
    TICKETS: (ref) => `/bookings/${ref}/tickets`,
    INVOICE: (ref) => `/bookings/${ref}/invoice`,
    ORGANIZER_LIST: "/bookings/organizer/all",
    ORGANIZER_CHECKIN: (ref) => `/bookings/organizer/${ref}/checkin`,
    WAITLIST: (eventId) => `/bookings/waitlist/${eventId}`,
    ADMIN_LIST: "/admin/bookings",
    ADMIN_CANCEL: (ref) => `/admin/bookings/${ref}/cancel`,
    ADMIN_REFUND: (ref) => `/admin/bookings/${ref}/refund`,
  },

  PAYMENTS: {
    INTENT: "/payments/intent",
    VERIFY: "/payments/verify",
    LIST: "/payments",
    METHODS: "/payments/methods",
    METHOD: (id) => `/payments/methods/${id}`,
    DETAIL: (id) => `/payments/${id}`,
    REFUND: (id) => `/payments/${id}/refund`,
    ADMIN_LIST: "/admin/payments",
    ADMIN_DETAIL: (id) => `/admin/payments/${id}`,
    ADMIN_REFUND: (id) => `/admin/payments/${id}/refund`,
  },

  PAYOUTS: {
    REQUEST: "/payouts/request",
  },

  TICKETS: {
    LIST: "/tickets",
    PUBLIC_VERIFY: (code) => `/tickets/verify/${code}`,
    DETAIL: (code) => `/tickets/${code}`,
    DOWNLOAD: (code) => `/tickets/${code}/download`,
    VALIDATE: (code) => `/tickets/${code}/validate`,
    TRANSFER: (code) => `/tickets/${code}/transfer`,
    CANCEL: (code) => `/tickets/${code}/cancel`,
  },

  SEARCH: {
    ROOT: "/search",
    AUTOCOMPLETE: "/search/autocomplete",
    TRENDING: "/search/trending",
    NEARBY: "/search/nearby",
    FACETS: "/search/facets",
    REINDEX: "/search/reindex",
    REINDEX_EVENT: (id) => `/search/reindex/${id}`,
    REMOVE_INDEX: (id) => `/search/index/${id}`,
  },

  NOTIFICATIONS: {
    LIST: "/notifications",
    DETAIL: (id) => `/notifications/${id}`,
    UNREAD: "/notifications/unread-count",
    MARK_READ: (id) => `/notifications/${id}/read`,
    MARK_ALL: "/notifications/read-all",
    DELETE: (id) => `/notifications/${id}`,
    CLEAR: "/notifications",
    PREFERENCES: "/notifications/preferences",
    PUSH_SUBSCRIBE: "/notifications/push/subscribe",
    PUSH_UNSUBSCRIBE: "/notifications/push/unsubscribe",
    VAPID_KEY: "/notifications/vapid-key",
  },

  MESSAGING: {
    CONVERSATIONS: "/messaging/conversations",
    CONVERSATION: (id) => `/messaging/conversations/${id}`,
    MESSAGES: (id) => `/messaging/conversations/${id}/messages`,
    MARK_READ: (id) => `/messaging/conversations/${id}/read`,
    UNREAD: "/messaging/unread-count",
  },

  ORGANIZERS: {
    PROFILE: (slug) => `/organizers/${slug}`,
    EVENTS: (slug) => `/organizers/${slug}/events`,
    OWN_PROFILE: "/organizer/profile",
    OWN_VERIFICATION: "/organizer/verification",
    DASHBOARD: "/organizer/dashboard",
    MY_EVENTS: "/organizer/events",
    MY_BOOKINGS: "/organizer/bookings",
    REVENUE: "/organizer/revenue",
    PAYOUTS: "/organizer/payouts",
    ANALYTICS_OVERVIEW: "/analytics/overview",
    ANALYTICS_REVENUE: "/analytics/revenue",
    ANALYTICS_TICKETS: "/analytics/tickets",
    ANALYTICS_EVENTS: "/analytics/events",
    ANALYTICS_EVENT: (id) => `/analytics/events/${id}`,
    ANALYTICS_AUDIENCE: "/analytics/audience",
    // Image upload (Cloudinary)
    LOGO_IMAGE: "/organizer/images/logo",
    BANNER_IMAGE: "/organizer/images/banner",
  },

  CATEGORIES: {
    LIST: "/categories",
    ADMIN_LIST: "/categories/admin/all",
    DETAIL: (slug) => `/categories/${slug}`,
    SUBS: (slug) => `/categories/${slug}/subcategories`,
    CREATE: "/categories",
    UPDATE: (slug) => `/categories/${slug}`,
    DELETE: (slug) => `/categories/${slug}`,
  },

  SUBCATEGORIES: {
    LIST: "/subcategories",
    ADMIN_LIST: "/subcategories/admin/all",
    DETAIL: (slug) => `/subcategories/${slug}`,
    CREATE: "/subcategories",
    UPDATE: (slug) => `/subcategories/${slug}`,
    DELETE: (slug) => `/subcategories/${slug}`,
  },
  EVENT_TYPES: {
    LIST: "/event-types",
    ADMIN_LIST: "/event-types/admin/all",
    DETAIL: (slug) => `/event-types/${slug}`,
    CREATE: "/event-types",
    UPDATE: (slug) => `/event-types/${slug}`,
    DELETE: (slug) => `/event-types/${slug}`,
  },

  REVIEWS: {
    LIST: "/reviews",
    SUMMARY: "/reviews/summary",
    CREATE: "/reviews",
    UPDATE: (id) => `/reviews/${id}`,
    DELETE: (id) => `/reviews/${id}`,
    MY: "/reviews/my",
    ADMIN_LIST: "/admin/reviews",
    ADMIN_DELETE: (id) => `/admin/reviews/${id}`,
    ADMIN_FLAG: (id) => `/admin/reviews/${id}/flag`,
  },

  CART: {
    ROOT: "/cart",
    ADD: "/cart/items",
    UPDATE: (id) => `/cart/items/${id}`,
    REMOVE: (id) => `/cart/items/${id}`,
    CLEAR: "/cart",
    APPLY_PROMO: "/cart/apply-promo",
    REMOVE_PROMO: "/cart/promo",
    CHECKOUT: "/cart/checkout",
  },

  PROMOTIONS: {
    VALIDATE: "/promotions/validate",
    ORGANIZER_LIST: "/promotions/organizer",
    ORGANIZER_CREATE: "/promotions/organizer",
    ORGANIZER_DETAIL: (id) => `/promotions/organizer/${id}`,
    ADMIN_LIST: "/admin/promotions",
    ADMIN_DISABLE: (id) => `/admin/promotions/${id}/disable`,
  },

  ANALYTICS: {
    OVERVIEW: "/analytics/overview",
    REVENUE: "/analytics/revenue",
    TICKETS: "/analytics/tickets",
    EVENTS: "/analytics/events",
    EVENT: (id) => `/analytics/events/${id}`,
    AUDIENCE: "/analytics/audience",
    ADMIN_OVERVIEW: "/admin/analytics/overview",
    ADMIN_REVENUE: "/admin/analytics/revenue",
    ADMIN_USERS: "/admin/analytics/users",
    ADMIN_EVENTS: "/admin/analytics/events",
    ADMIN_ORGANIZERS: "/admin/analytics/organizers",
  },

  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    DASHBOARD_STATS: "/admin/dashboard/stats",
    USERS: "/admin/users",
    USER: (id) => `/admin/users/${id}`,
    BAN_USER: (id) => `/admin/users/${id}/ban`,
    UNBAN_USER: (id) => `/admin/users/${id}/unban`,
    USER_ROLE: (id) => `/admin/users/${id}/role`,
    ORGANIZERS: "/admin/organizers",
    ORGANIZER: (id) => `/admin/organizers/${id}`,
    VERIFY_ORGANIZER: (id) => `/admin/organizers/${id}/verify`,
    REJECT_ORGANIZER: (id) => `/admin/organizers/${id}/reject`,
    SUSPEND_ORGANIZER: (id) => `/admin/organizers/${id}/suspend`,
    BOOKINGS: "/admin/bookings",
    BOOKING: (id) => `/admin/bookings/${id}`,
    BOOKING_CANCEL: (ref) => `/admin/bookings/${ref}/cancel`,
    BOOKING_REFUND: (ref) => `/admin/bookings/${ref}/refund`,
    PAYMENTS: "/admin/payments",
    PAYMENT: (id) => `/admin/payments/${id}`,
    PAYMENT_REFUND: (id) => `/admin/payments/${id}/refund`,
    REVIEWS: "/admin/reviews",
    REVIEW: (id) => `/admin/reviews/${id}`,
    REVIEW_FLAG: (id) => `/admin/reviews/${id}/flag`,
    ANALYTICS_OVERVIEW: "/admin/analytics/overview",
    ANALYTICS_REVENUE: "/admin/analytics/revenue",
    ANALYTICS_USERS: "/admin/analytics/users",
    ANALYTICS_EVENTS: "/admin/analytics/events",
    ANALYTICS_ORGANIZERS: "/admin/analytics/organizers",
    PROMOTIONS: "/admin/promotions",
    PROMOTION_DISABLE: (id) => `/admin/promotions/${id}/disable`,
    SYSTEM_HEALTH: "/admin/system/health",
    SYSTEM_METRICS: "/admin/system/metrics",
    FEATURE_FLAGS: "/admin/feature-flags",
    REPORTS: "/admin/reports",
    REPORT: (id) => `/admin/reports/${id}`,
    REPORT_ACTION: (id) => `/admin/reports/${id}`,
    SYSTEM_SETTINGS: "/admin/system/settings",
    SYSTEM_LOGS: "/admin/system/logs",
    SYSTEM_SESSIONS: "/admin/system/sessions",
    SYSTEM_SECURITY_ALERTS: "/admin/system/security-alerts",
    SYSTEM_AUDIT_LOGS: "/admin/system/audit-logs",
    PAYOUTS: "/admin/payouts",
    PAYOUT: (id) => `/admin/payouts/${id}`,
    EVENTS: "/admin/events",
    EVENT: (id) => `/admin/events/${id}`,
  },

  MODERATOR: {
    DASHBOARD: "/moderator/dashboard",
    USERS: "/moderator/users",
    SUSPEND_USER: (id) => `/moderator/users/${id}/suspend`,
    UNSUSPEND_USER: (id) => `/moderator/users/${id}/unsuspend`,
    WARN_USER: (id) => `/moderator/users/${id}/warn`,
    REPORTS: "/moderator/reports",
    REPORT_RESOLVE: (id) => `/moderator/reports/${id}/resolve`,
    EVENTS_PENDING: "/moderator/events/pending",
    APPROVE_EVENT: (id) => `/moderator/events/${id}/approve`,
    REJECT_EVENT: (id) => `/moderator/events/${id}/reject`,
  },

  SUPER_ADMIN: {
    DASHBOARD: "/super-admin/dashboard",
    ADMINS: "/super-admin/admins",
    USERS: "/super-admin/users",
    ASSIGN_ADMIN: (id) => `/super-admin/admins/${id}/assign`,
    REVOKE_ADMIN: (id) => `/super-admin/admins/${id}/revoke`,
    USER_ROLE: (id) => `/super-admin/users/${id}/role`,
    SETTINGS: "/super-admin/settings",
    AUDIT_LOGS: "/super-admin/audit-logs",
    FORCE_LOGOUT_ALL: "/super-admin/force-logout-all",
    HEALTH: "/super-admin/health",
  },

  LOCATIONS: {
    LIST: "/locations",
    CITIES: "/locations/cities",
    COUNTRIES: "/locations/countries",
    REVERSE: "/locations/reverse",
    DETAIL: (slug) => `/locations/${slug}`,
  },

  TAGS: {
    LIST: "/tags",
    POPULAR: "/tags/popular",
    DETAIL: (slug) => `/tags/${slug}`,
  },

  SUPPORT: {
    CONTACT: "/support/contact",
  },
};

export default ENDPOINTS;
