const PERMISSIONS = Object.freeze({
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_LIST: 'user:list',
  USER_BLOCK: 'user:block',
  USER_VERIFY: 'user:verify',

  PROFILE_READ: 'profile:read',
  PROFILE_UPDATE: 'profile:update',
  PROFILE_DELETE: 'profile:delete',

  EVENT_CREATE: 'event:create',
  EVENT_READ: 'event:read',
  EVENT_UPDATE: 'event:update',
  EVENT_DELETE: 'event:delete',
  EVENT_LIST: 'event:list',
  EVENT_PUBLISH: 'event:publish',
  EVENT_CANCEL: 'event:cancel',
  EVENT_APPROVE: 'event:approve',
  EVENT_REJECT: 'event:reject',
  EVENT_FEATURE: 'event:feature',

  BOOKING_CREATE: 'booking:create',
  BOOKING_READ: 'booking:read',
  BOOKING_UPDATE: 'booking:update',
  BOOKING_CANCEL: 'booking:cancel',
  BOOKING_LIST: 'booking:list',
  BOOKING_APPROVE: 'booking:approve',
  BOOKING_REFUND: 'booking:refund',

  TICKET_GENERATE: 'ticket:generate',
  TICKET_VALIDATE: 'ticket:validate',
  TICKET_TRANSFER: 'ticket:transfer',
  TICKET_CANCEL: 'ticket:cancel',
  TICKET_READ: 'ticket:read',

  PAYMENT_PROCESS: 'payment:process',
  PAYMENT_READ: 'payment:read',
  PAYMENT_REFUND: 'payment:refund',
  PAYMENT_LIST: 'payment:list',

  PAYOUT_REQUEST: 'payout:request',
  PAYOUT_APPROVE: 'payout:approve',
  PAYOUT_PROCESS: 'payout:process',
  PAYOUT_READ: 'payout:read',
  PAYOUT_LIST: 'payout:list',

  ORGANIZER_APPLY: 'organizer:apply',
  ORGANIZER_READ: 'organizer:read',
  ORGANIZER_UPDATE: 'organizer:update',
  ORGANIZER_APPROVE: 'organizer:approve',
  ORGANIZER_REJECT: 'organizer:reject',
  ORGANIZER_SUSPEND: 'organizer:suspend',

  CATEGORY_CREATE: 'category:create',
  CATEGORY_READ: 'category:read',
  CATEGORY_UPDATE: 'category:update',
  CATEGORY_DELETE: 'category:delete',
  CATEGORY_LIST: 'category:list',
  EVENT_TYPE_CREATE: 'event_type:create',
  EVENT_TYPE_READ: 'event_type:read',
  EVENT_TYPE_UPDATE: 'event_type:update',
  EVENT_TYPE_DELETE: 'event_type:delete',
  EVENT_TYPE_LIST: 'event_type:list',

  REVIEW_CREATE: 'review:create',
  REVIEW_READ: 'review:read',
  REVIEW_UPDATE: 'review:update',
  REVIEW_DELETE: 'review:delete',
  REVIEW_MODERATE: 'review:moderate',
  REVIEW_REPLY: 'review:reply',

  NOTIFICATION_READ: 'notification:read',
  NOTIFICATION_UPDATE: 'notification:update',
  NOTIFICATION_DELETE: 'notification:delete',
  NOTIFICATION_SEND: 'notification:send',

  ANALYTICS_READ: 'analytics:read',
  ANALYTICS_EXPORT: 'analytics:export',
  ANALYTICS_VIEW_OWN: 'analytics:view_own',
  ANALYTICS_VIEW_ALL: 'analytics:view_all',

  REPORT_CREATE: 'report:create',
  REPORT_READ: 'report:read',
  REPORT_UPDATE: 'report:update',
  REPORT_RESOLVE: 'report:resolve',
  REPORT_DELETE: 'report:delete',

  ADMIN_CREATE: 'admin:create',
  ADMIN_READ: 'admin:read',
  ADMIN_UPDATE: 'admin:update',
  ADMIN_DELETE: 'admin:delete',
  ADMIN_LIST: 'admin:list',

  SYSTEM_SETTINGS: 'system:settings',
  SYSTEM_LOGS: 'system:logs',
  SYSTEM_BACKUP: 'system:backup',
  SYSTEM_RESTORE: 'system:restore',
  SYSTEM_MONITOR: 'system:monitor',
  SYSTEM_SECURITY: 'system:security',
  SYSTEM_SESSION_REVOKE: 'system:session_revoke',

  ROLE_ASSIGN: 'role:assign',
  ROLE_REVOKE: 'role:revoke',
  ROLE_LIST: 'role:list',

  AUDIT_READ: 'audit:read',
  AUDIT_EXPORT: 'audit:export',
});

const unique = (items) => [...new Set(items)];

const baseUserPermissions = [
  PERMISSIONS.PROFILE_READ,
  PERMISSIONS.PROFILE_UPDATE,
  PERMISSIONS.EVENT_READ,
  PERMISSIONS.EVENT_LIST,
  PERMISSIONS.BOOKING_CREATE,
  PERMISSIONS.BOOKING_READ,
  PERMISSIONS.BOOKING_CANCEL,
  PERMISSIONS.TICKET_READ,
  PERMISSIONS.PAYMENT_PROCESS,
  PERMISSIONS.PAYMENT_READ,
  PERMISSIONS.REVIEW_CREATE,
  PERMISSIONS.REVIEW_READ,
  PERMISSIONS.REVIEW_UPDATE,
  PERMISSIONS.NOTIFICATION_READ,
  PERMISSIONS.NOTIFICATION_UPDATE,
  PERMISSIONS.REPORT_CREATE,
  PERMISSIONS.ORGANIZER_APPLY,
];

const organizerPermissions = [
  ...baseUserPermissions,
  PERMISSIONS.EVENT_CREATE,
  PERMISSIONS.EVENT_UPDATE,
  PERMISSIONS.EVENT_DELETE,
  PERMISSIONS.EVENT_PUBLISH,
  PERMISSIONS.EVENT_CANCEL,
  PERMISSIONS.BOOKING_LIST,
  PERMISSIONS.TICKET_GENERATE,
  PERMISSIONS.TICKET_VALIDATE,
  PERMISSIONS.PAYOUT_REQUEST,
  PERMISSIONS.PAYOUT_READ,
  PERMISSIONS.ANALYTICS_VIEW_OWN,
  PERMISSIONS.REVIEW_REPLY,
  PERMISSIONS.ORGANIZER_UPDATE,
];

const moderatorPermissions = [
  ...baseUserPermissions,
  PERMISSIONS.USER_READ,
  PERMISSIONS.USER_BLOCK,
  PERMISSIONS.REPORT_READ,
  PERMISSIONS.REPORT_UPDATE,
  PERMISSIONS.REPORT_RESOLVE,
  PERMISSIONS.EVENT_APPROVE,
  PERMISSIONS.EVENT_REJECT,
  PERMISSIONS.EVENT_FEATURE,
  PERMISSIONS.REVIEW_MODERATE,
  PERMISSIONS.REVIEW_DELETE,
  PERMISSIONS.CATEGORY_READ,
  PERMISSIONS.CATEGORY_LIST,
  PERMISSIONS.ORGANIZER_READ,
];

const adminPermissions = unique([
  ...organizerPermissions,
  ...moderatorPermissions,
  PERMISSIONS.USER_CREATE,
  PERMISSIONS.USER_UPDATE,
  PERMISSIONS.USER_LIST,
  PERMISSIONS.USER_VERIFY,
  PERMISSIONS.ORGANIZER_APPROVE,
  PERMISSIONS.ORGANIZER_REJECT,
  PERMISSIONS.ORGANIZER_SUSPEND,
  PERMISSIONS.CATEGORY_CREATE,
  PERMISSIONS.CATEGORY_UPDATE,
  PERMISSIONS.CATEGORY_DELETE,
  PERMISSIONS.PAYMENT_LIST,
  PERMISSIONS.PAYMENT_REFUND,
  PERMISSIONS.PAYOUT_APPROVE,
  PERMISSIONS.PAYOUT_PROCESS,
  PERMISSIONS.ANALYTICS_READ,
  PERMISSIONS.ANALYTICS_VIEW_ALL,
  PERMISSIONS.ANALYTICS_EXPORT,
  PERMISSIONS.ADMIN_READ,
  PERMISSIONS.ADMIN_LIST,
  PERMISSIONS.AUDIT_READ,
  PERMISSIONS.SYSTEM_MONITOR,
  PERMISSIONS.SYSTEM_LOGS,
  PERMISSIONS.SYSTEM_SESSION_REVOKE,
]);

const ROLE_PERMISSIONS_MAP = Object.freeze({
  user: unique(baseUserPermissions),
  organizer: unique(organizerPermissions),
  moderator: unique(moderatorPermissions),
  admin: unique(adminPermissions),
  super_admin: ['*'],
});

// Permission groups for better organization
const PERMISSION_GROUPS = {
  USER: "user",
  PROFILE: "profile",
  EVENT: "event",
  BOOKING: "booking",
  TICKET: "ticket",
  PAYMENT: "payment",
  PAYOUT: "payout",
  ORGANIZER: "organizer",
  CATEGORY: "category",
  REVIEW: "review",
  NOTIFICATION: "notification",
  ANALYTICS: "analytics",
  REPORT: "report",
  ADMIN: "admin",
  SYSTEM: "system",
  ROLE: "role",
  AUDIT: "audit",
  EVENT_TYPE: "event_type",
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS_MAP,
  PERMISSION_GROUPS,
};
